# Generated by Django 2.2.12 on 2023-04-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('text', models.CharField(db_column='text', max_length=999)),
                ('likes', models.IntegerField(db_column='likes', default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='username', max_length=999)),
                ('email', models.CharField(db_column='email', max_length=999)),
                ('password', models.CharField(db_column='password', max_length=999)),
                ('permission', models.IntegerField(db_column='permission', default=0)),
                ('token', models.CharField(db_column='token', max_length=999, null=True)),
                ('token_time', models.DateTimeField(db_column='token_time', null=True)),
            ],
        ),
    ]
